CREATE TABLE IF NOT EXISTS accounts(
  id VARCHAR(255) NOT NULL primary key COMMENT 'primary key',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created',
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update',
  name VARCHAR(255) COMMENT 'User Name',
  email VARCHAR(255) COMMENT 'User Email',
  picture VARCHAR(500) COMMENT 'User Picture',
  coverImg VARCHAR(500) COMMENT 'User Cover Image'
) default charset utf8mb4 COMMENT '';

CREATE TABLE IF NOT EXISTS keeps(
 id INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'Primary Key',
 createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created',
 updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update',
 name VARCHAR(255) NOT NULL COMMENT 'Name',
 description VARCHAR(500) NOT NULL COMMENT 'Description',
 img VARCHAR(500) NOT NULL COMMENT 'Image',
 creatorId VARCHAR(255) NOT NULL COMMENT 'Creator Id',
 views INT NOT NULL DEFAULT 0,

 FOREIGN KEY (creatorId) REFERENCES accounts(id) ON DELETE CASCADE
) default charset utf8mb4 COMMENT '';

CREATE TABLE IF NOT EXISTS vaults(
 id INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'Primary Key',
 createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created',
 updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update',
 name VARCHAR(255) NOT NULL COMMENT 'Name',
 description VARCHAR(500) NOT NULL COMMENT 'Description',
 img VARCHAR(500) NOT NULL COMMENT 'Image',
 isPrivate BOOLEAN NOT NULL DEFAULT false COMMENT 'Is Private',
 creatorId VARCHAR(255) NOT NULL COMMENT 'Creator Id',

 FOREIGN KEY (creatorId) REFERENCES accounts(id) ON DELETE CASCADE
) default charset utf8mb4 COMMENT '';

DROP TABLE keeps;